### ISSUE TITLE
Random spherecast hits on non damagables.

### ISSUE THREAD

**Issue by LunaMoonDev18** [LunaMoonDev18/Davacis#3]

**Comment by inofearu** [comment]
branch is hit-reg-fix

**Comment by LunaMoonDev18** [comment]
Issue related to angle test equipment

**Comment by LunaMoonDev18** [comment]
Issue appears on any geometry in-line with the player

**Comment by LunaMoonDev18** [comment]
Debug drawing of spherecast and real spherecast not aligned, real spherecast appears to travel straight from player

**Comment by LunaMoonDev18** [comment]
"Camera.main" missing from "Camera.main.transform.forward" at line 26 in SwordSwing.cs
